#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.
# 如果调用系统调用，会调用到usys.S，然后调用到usys.pl，最后调用到kernel/syscall.h，最后调用到kernel/syscall.c
# 比如fork，会进入entry然后将进程的trapframe的a7设置为SYS_fork，然后ecall进入内核trap，所以就会按照trap的流程调用到trap.c中的usertrap，这个函数调用到了syscall.c中的syscalls函数
# usertrap还会保存返回值寄存器a0，然后返回到用户态

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n"; # a7 = syscall number
    print " ecall\n"; # uservec -> usertrap -> syscall
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("pause");
entry("uptime");
